blog/urls.py
from django.urls import path
from .views import (BlogList,
                    BlogDetail,
                    CreateBlog,
                    UpdateBlog,
                    DeleteBlog,
)


app_name = 'blog'


urlpatterns = [
    path('<slug>/delete/create/', DeleteBlog.as_view(), name='create'),
    path('', BlogList.as_view(), name='list'),
    path('create/', CreateBlog.as_view(), name='delete'),
    path('<slug>/update/', UpdateBlog.as_view(), name='update'),
    path('detail/<slug>/', BlogDetail.as_view(), name='detail'),
]

blogme/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify


User = get_user_model()

# Create your models here.
class Blog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='blog/images/')
    slug = models.SlugField()
    body = models.TextField()
    posted = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)
     

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .models import Blog


# Create your views here.
class BlogList(generic.ListView):
    model = Blog
    template_name = 'blog/blog_list.html'


class BlogDetail(generic.DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'


class CreateBlog(generic.CreateView):
    model = Blog
    template_name = 'blog/blog_form.html'
    success_url = reverse_lazy('blog:list')


class UpdateBlog(generic.UpdateView):
    model = Blog
    template_name = 'blog/blog_form.html'
    success_url = reverse_lazy('blog:list')


class DeleteBlog(generic.DeleteView):
    model = Blog
    template_name = 'blog/blog_delete.html'
    success_url = reverse_lazy('blog:list')

blog/templates/blog/blog_delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure you want to delete this post?
    <input type="submit" value="Yes">
    <a href="{% url 'blog:detail' object.slug %}"></a>
</form>

blog/templates/blog/blog_detail.html
<a href="{% url 'blog:list' %}">Back</a>
<h3>{{ object.title }} <span>By: {{ object.user }}</span></h3>

<time>{{ object.timestamp }}</time>
<img src="{{ object.image.url }}" alt="Post Image">
<p>{{ object.body }}</p>
<a href="{% url 'blog:list' %}">Back</a>

blog/templates/blog/blog_form.html
<form method="POST">
    {% csrf_token %}
    {{ form.title }}<br>
    {{ form.body }}<br>
    {{ form.image }}<br>
    {{ form.posted }}<br>
    {{ form.title }}<br>

    <input type="submit" value="POST" >
</form>

blog/templates/blog/blog_list.html
<h3>List of Posts</h3>
<ul>
    {% for item in object_list %}
        <li><a href="{% url 'blog:detail' object.slug %}" >{{ item.title }}</a></li>
    {% empty %}
        <li><em>Oops! No post yet.</em></li>
    {% endfor %}

</ul>

blog/templates/blog\/blog_detail.html
<h3>{{ object.title }} <span>By: {{ object.user }}</span></h3>

<time>{{ object.timestamp }}</time>
<img src="{{ object.image.url }}" alt="Post Image">
<p>{{ object.body }}</p>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tosin Blog</title>
</head>
<body>
    
</body>
</html>